simulation_dir = "."

[scba]
max_iterations = 21
mixing_factor = 0.75
phonon = true

[electron] # ===========================================================
# 0.2 V Potential difference.
left_fermi_level = -3.6  # eV
right_fermi_level = -3.8 # eV

fermi_level = -3.6                        # eV
conduction_band_edge = -3.566382123573606 # eV
valence_band_edge = -4.174109778287768    # eV

solver.algorithm = "rgf"
solver.max_batch_size = 1000
solver.compute_current = true # Compute Meir-Wingreen current.

obc.algorithm = "spectral"
obc.nevp_solver = "beyn"
obc.block_sections = 1

# Parameters for Beyn's method.
obc.num_ref_iterations = 3
obc.max_decay = 15
obc.min_decay = 1e-3
obc.r_o = 10
obc.r_i = 0.8
obc.m_0 = 31
obc.num_quad_points = 31

# Use memoization to speed up the OBC calculation.
obc.memoizer.enable = true


[phonon] # =============================================================
model = "pseudo-scattering"
phonon_energy = 40e-3         # eV
deformation_potential = 75e-3 # eV
