simulation_dir = "."

[scba]
max_iterations = 5
mixing_factor = 1.0
phonon = true

[electron]
left_fermi_level = -3.9  # eV
right_fermi_level = -3.8 # eV
solver = "rgf"
eta = 1e-5

[electron.obc]
algorithm = "spectral" # "sancho-rubio"

nevp_solver = "beyn"
r_o = 10.0
r_i = 0.9
c_hat = 25
num_quad_points = 26

[electron.obc.memoizer]
enable = true
num_ref_iterations = 4
convergence_tol = 1e-2


[phonon]
model = "pseudo-scattering"
phonon_energy = 40e-3         # eV
deformation_potential = 75e-3 # eV
