simulation_dir = "/home/awinka/Python/new_quatrex/quatrex/examples/w90/cnt"

[scba]
max_iterations = 5
mixing_factor = 1.0
phonon = false
coulomb_screening = true

[electron]
left_fermi_level = -3.9  # eV
right_fermi_level = -3.9 # eV
solver = "rgf"
eta = 1e-5

[electron.obc]
algorithm = "sancho-rubio" # "spectral"

nevp_solver = "beyn"
r_o = 10.0
r_i = 0.9
c_hat = 25
num_quad_points = 26

[electron.obc.memoizer]
enable = true
num_ref_iterations = 4
convergence_tol = 1e-2

[coulomb_screening]
solver = "rgf"

[coulomb_screening.obc]
algorithm = "sancho-rubio" # "spectral"
block_sections = 1

[phonon]
model = "pseudo-scattering"
phonon_energy = 40e-3         # eV
deformation_potential = 75e-3 # eV
