simulation_dir = "."

[scba]
min_iterations = 1
max_iterations = 21
mixing_factor = 0.5
coulomb_screening = true
phonon = false

[electron]
left_fermi_level = -3.6  # eV
right_fermi_level = -3.8 # eV

fermi_level = -3.6                        # eV
conduction_band_edge = -3.566382123573606 # eV
valence_band_edge = -4.174109778287768    # eV

band_edge_tracking = "eigenvalues"

solver = "rgf"
eta_obc = 0
eta = 1e-12

[electron.obc]
algorithm = "spectral"

nevp_solver = "beyn"

# By pure guesswork:
num_ref_iterations = 2
max_decay = 5
min_decay = 1e-3
r_o = 10
r_i = 0.8
m_0 = 32
num_quad_points = 30

[electron.obc.memoizer]
enable = false

[coulomb_screening]
solver = "rgf"

interaction_cutoff = 8 # Å

[coulomb_screening.obc]
algorithm = "spectral"
block_sections = 1
nevp_solver = "full"

num_ref_iterations = 10
max_decay = 14
min_decay = 1e-4

[coulomb_screening.obc.memoizer]
enable = false

[coulomb_screening.lyapunov]
algorithm = "spectral"

[coulomb_screening.lyapunov.memoizer]
enable = false

[phonon]
model = "pseudo-scattering"
phonon_energy = 1e-3         # eV
deformation_potential = 5e-3 # eV
