simulation_dir = ""

[scba]
max_iterations = 2
mixing_factor = 0.25
phonon = false
coulomb_screening = true

[electron]
number_of_kpoints = [1, 3, 1]
left_fermi_level = -1.1  # eV
right_fermi_level = -1.1 # eV
fermi_level = -1.1 # eV
conduction_band_edge = -0.3187 # eV
valence_band_edge = -2.0026 # eV
solver = "rgf"
eta = 1e-8

[electron.obc]
algorithm = "spectral" # "sancho-rubio"

nevp_solver = "full"  # "beyn"
r_o = 1000.0
r_i = 0.9
c_hat = 25
num_quad_points = 26

[electron.obc.memoizer]
enable = true
num_ref_iterations = 4
convergence_tol = 1e-2

[coulomb_screening]
solver = "rgf"

[coulomb_screening.obc]
algorithm = "spectral" # "sancho-rubio"
block_sections = 1

[phonon]
model = "pseudo-scattering"
phonon_energy = 40e-3         # eV
deformation_potential = 75e-3 # eV
